import { generateJson } from './gemini.js';
import { env } from '../config/env.js';
import { verdict } from '../utils/scoring.js';

/* ============================================================
   AI DECISION ENGINE — the integration point for module 7
   (INDUSTRY REPORT). Report data goes in, a structured executive
   decision comes out.

   Like the SpyFu integration this degrades rather than throws:
   with no GEMINI_API_KEY it returns a deterministic heuristic
   verdict flagged `live: false`, so the pipeline still completes.
   ============================================================ */

/** JSON Schema the model is constrained to — guarantees a parseable decision. */
const DECISION_SCHEMA = {
  type: 'object',
  properties: {
    decision: { type: 'integer', enum: [0, 1] },
    label: { type: 'string', enum: ['PROCEED', 'PIVOT'] },
    score: { type: 'integer' },
    headline: { type: 'string' },
    rationale: { type: 'string' },
    strengths: { type: 'array', items: { type: 'string' } },
    risks: { type: 'array', items: { type: 'string' } },
    nextActions: { type: 'array', items: { type: 'string' } },
  },
  required: ['decision', 'label', 'score', 'headline', 'rationale', 'strengths', 'risks', 'nextActions'],
  additionalProperties: false,
};

const SYSTEM_PROMPT = `You are the decision engine for The Conscious Orbit, a venture strategy platform.

You receive the consolidated output of a venture's intelligence pipeline: customer
discovery, sector profiling, TAM/SAM/SOM market sizing, feasibility, pricing,
competitor research, business-model validation, go-to-market, and OKRs.

Return a single sovereign verdict on whether the venture should proceed.

Rules:
- Ground every claim in the supplied data. If a module is missing, say so in the
  rationale rather than inventing a figure.
- "score" is 0-100 and must be consistent with "decision" (1/PROCEED at 60+, else 0/PIVOT).
- Keep "headline" to one sentence. Keep each list to 3-5 concrete, specific items.
- Prefer naming the binding constraint over listing generic startup advice.`;

/**
 * Ask the model for an executive decision on a report.
 *
 * @param {object} payload Consolidated report + module outputs.
 * @param {number} payload.heuristicScore Score computed from the modules, used
 *   as the fallback and given to the model as a prior.
 * @returns {Promise<object>} Always resolves; check `.live`.
 */
export async function generateDecision(payload) {
  const { heuristicScore = 0, ...context } = payload;

  if (!env.gemini.enabled) {
    return {
      ...heuristicDecision(heuristicScore, context),
      live: false,
      model: null,
      note: 'GEMINI_API_KEY not configured — returning a heuristic verdict computed from module scores.',
    };
  }

  const userPrompt = [
    'Here is the consolidated pipeline output for one venture.',
    `The pipeline's own weighted score is ${heuristicScore}/100 — treat it as a prior, not gospel.`,
    '',
    '```json',
    JSON.stringify(context, null, 2),
    '```',
    '',
    'Return the executive decision.',
  ].join('\n');

  const result = await generateJson(SYSTEM_PROMPT, userPrompt, DECISION_SCHEMA);
  if (!result) {
    return {
      ...heuristicDecision(heuristicScore, context),
      live: false,
      model: env.gemini.model,
      note: 'Gemini call failed or returned no usable answer — returning heuristic verdict.',
    };
  }

  const parsed = { ...result.data };
  // Gemini returns enum values as strings; the platform stores decision as 0/1.
  if (typeof parsed.decision === 'string') {
    parsed.decision = ['1', 'GO', 'PROCEED'].includes(parsed.decision.trim()) ? 1 : 0;
  }
  if (typeof parsed.score === 'string') {
    const n = Number(parsed.score);
    parsed.score = Number.isFinite(n) ? Math.max(0, Math.min(100, Math.round(n))) : heuristicScore;
  }

  return {
    ...parsed,
    live: true,
    model: result.model,
    note: 'Generated by the Gemini decision engine.',
  };
}

/** Deterministic fallback so the pipeline never stalls on a missing key. */
function heuristicDecision(score, context) {
  const v = verdict(score);
  const modules = Object.keys(context.modules ?? {});
  return {
    decision: v.decision,
    label: v.label,
    score: v.score,
    headline:
      v.decision === 1
        ? `Weighted pipeline score of ${v.score}/100 clears the ${v.threshold} threshold.`
        : `Weighted pipeline score of ${v.score}/100 falls short of the ${v.threshold} threshold.`,
    rationale:
      `Computed from ${modules.length} completed module${modules.length === 1 ? '' : 's'} ` +
      `(${modules.join(', ') || 'none'}). No language model was consulted.`,
    strengths: [],
    risks: modules.length < 5 ? ['Verdict rests on an incomplete pipeline — run the remaining modules.'] : [],
    nextActions: ['Configure GEMINI_API_KEY to receive a reasoned executive decision.'],
  };
}
