import Anthropic from '@anthropic-ai/sdk';
import { env } from '../config/env.js';
import { verdict } from '../utils/scoring.js';

/* ============================================================
   AI DECISION ENGINE — the integration point for module 7
   (INDUSTRY REPORT). Report data goes in, a structured executive
   decision comes out.

   Like the SpyFu integration this degrades rather than throws:
   with no ANTHROPIC_API_KEY it returns a deterministic heuristic
   verdict flagged `live: false`, so the pipeline still completes.
   ============================================================ */

let client = null;
function getClient() {
  if (!env.anthropic.enabled) return null;
  // The SDK reads ANTHROPIC_API_KEY itself; passing it explicitly keeps
  // configuration in one place.
  client ??= new Anthropic({ apiKey: env.anthropic.apiKey });
  return client;
}

/** JSON Schema the model is constrained to — guarantees a parseable decision. */
const DECISION_SCHEMA = {
  type: 'object',
  properties: {
    decision: { type: 'integer', enum: [0, 1] },
    label: { type: 'string', enum: ['PROCEED', 'PIVOT'] },
    score: { type: 'integer' },
    headline: { type: 'string' },
    rationale: { type: 'string' },
    strengths: { type: 'array', items: { type: 'string' } },
    risks: { type: 'array', items: { type: 'string' } },
    nextActions: { type: 'array', items: { type: 'string' } },
  },
  required: ['decision', 'label', 'score', 'headline', 'rationale', 'strengths', 'risks', 'nextActions'],
  additionalProperties: false,
};

const SYSTEM_PROMPT = `You are the decision engine for The Conscious Orbit, a venture strategy platform.

You receive the consolidated output of a venture's intelligence pipeline: customer
discovery, sector profiling, TAM/SAM/SOM market sizing, feasibility, pricing,
competitor research, business-model validation, go-to-market, and OKRs.

Return a single sovereign verdict on whether the venture should proceed.

Rules:
- Ground every claim in the supplied data. If a module is missing, say so in the
  rationale rather than inventing a figure.
- "score" is 0-100 and must be consistent with "decision" (1/PROCEED at 60+, else 0/PIVOT).
- Keep "headline" to one sentence. Keep each list to 3-5 concrete, specific items.
- Prefer naming the binding constraint over listing generic startup advice.`;

/**
 * Ask the model for an executive decision on a report.
 *
 * @param {object} payload Consolidated report + module outputs.
 * @param {number} payload.heuristicScore Score computed from the modules, used
 *   as the fallback and given to the model as a prior.
 * @returns {Promise<object>} Always resolves; check `.live`.
 */
export async function generateDecision(payload) {
  const { heuristicScore = 0, ...context } = payload;
  const anthropic = getClient();

  if (!anthropic) {
    return {
      ...heuristicDecision(heuristicScore, context),
      live: false,
      model: null,
      note: 'ANTHROPIC_API_KEY not configured — returning a heuristic verdict computed from module scores.',
    };
  }

  try {
    const response = await anthropic.messages.create({
      model: env.anthropic.model,
      max_tokens: 16000,
      thinking: { type: 'adaptive' },
      output_config: { format: { type: 'json_schema', schema: DECISION_SCHEMA } },
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: [
            'Here is the consolidated pipeline output for one venture.',
            'The pipeline\'s own weighted score is ' + heuristicScore + '/100 — treat it as a prior, not gospel.',
            '',
            '```json',
            JSON.stringify(context, null, 2),
            '```',
            '',
            'Return the executive decision.',
          ].join('\n'),
        },
      ],
    });

    // Safety classifiers can decline; check before reading content.
    if (response.stop_reason === 'refusal') {
      return {
        ...heuristicDecision(heuristicScore, context),
        live: false,
        model: env.anthropic.model,
        note: `Model declined to answer (${response.stop_details?.category ?? 'unspecified'}) — returning heuristic verdict.`,
      };
    }

    const text = response.content.find((b) => b.type === 'text')?.text ?? '';
    const parsed = JSON.parse(text);

    return {
      ...parsed,
      live: true,
      model: response.model,
      usage: {
        inputTokens: response.usage?.input_tokens,
        outputTokens: response.usage?.output_tokens,
      },
      note: 'Generated by the AI decision engine.',
    };
  } catch (error) {
    return {
      ...heuristicDecision(heuristicScore, context),
      live: false,
      model: env.anthropic.model,
      note: `AI decision call failed (${error.message}) — returning heuristic verdict.`,
    };
  }
}

/** Deterministic fallback so the pipeline never stalls on a missing key. */
function heuristicDecision(score, context) {
  const v = verdict(score);
  const modules = Object.keys(context.modules ?? {});
  return {
    decision: v.decision,
    label: v.label,
    score: v.score,
    headline:
      v.decision === 1
        ? `Weighted pipeline score of ${v.score}/100 clears the ${v.threshold} threshold.`
        : `Weighted pipeline score of ${v.score}/100 falls short of the ${v.threshold} threshold.`,
    rationale:
      `Computed from ${modules.length} completed module${modules.length === 1 ? '' : 's'} ` +
      `(${modules.join(', ') || 'none'}). No language model was consulted.`,
    strengths: [],
    risks: modules.length < 5 ? ['Verdict rests on an incomplete pipeline — run the remaining modules.'] : [],
    nextActions: ['Configure ANTHROPIC_API_KEY to receive a reasoned executive decision.'],
  };
}
